/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pgy.ui;
import com.pgy.businesslogic.Cliente;
import com.pgy.dataaccess.Conexion;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JTable;



/**
 *
 * @author imdan
 */
public final class VentanaHistorial extends javax.swing.JFrame {
    DefaultTableModel registro;
    public void tablaRegistro() {
    if (tableRegistro != null) {
        this.setLocationRelativeTo(null);
        registro = new DefaultTableModel();
        registro.addColumn("id_transaccion");
        registro.addColumn("cuenta_origen");
        registro.addColumn("monto");
        registro.addColumn("cuenta_destino");
        registro.addColumn("fecha_hora");
        tableRegistro.setModel(registro);
    } else {
        // Manejar la situación cuando tableRegistro es null
        System.err.println("tableRegistro es null. Asegúrate de que esté inicializado correctamente.");
    }
}

    public DefaultTableModel getRegistro() {
        return registro;
    }

    public void setRegistro(DefaultTableModel registro) {
        this.registro = registro;
    }

    public JTable getTableRegistro() {
        return tableRegistro;
    }

    public void setTableRegistro(JTable tableRegistro) {
        this.tableRegistro = tableRegistro;
    }

    public VentanaHistorial(DefaultTableModel registro) {
        this.registro = registro;
    }
    /**
     * Creates new form VentanaHistorial
     */
    
    public Cliente cliente;
    public VentanaHistorial(Cliente cliente) {
        initComponents();
        this.setSize(800,600);
        this.setTitle("West Bank");
        this.cliente=cliente;
        this.registro = new DefaultTableModel();
        tablaRegistro();
        llenarTabla();
    }
    public VentanaHistorial() {
        initComponents();
        this.setSize(800,600);
        this.setTitle("West Bank");
    }
    
    // Método para llenar la tabla con los datos de la base de datos
    public void llenarTabla() {
        // Limpiar el modelo de la tabla
//        registro.setRowCount(0);

        // Obtener datos de la base de datos y agregarlos al modelo
        try {
            Connection conexion = Conexion.obtenerConexion();
            if (conexion == null) {
                JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Consulta SQL para obtener los datos de la tabla transferencia
            String consulta = "SELECT id_transaccion, cuenta_origen, monto, cuenta_destino, fecha_hora FROM transferencia WHERE rut = ?";
            try (PreparedStatement preparedStatement = conexion.prepareStatement(consulta)) {
                preparedStatement.setString(1, cliente.getRut());
                String rut = cliente.getRut();
                System.out.println("Rut Ventana historial: " + rut);
                // Ejecutar la consulta
                try (ResultSet resultSet = preparedStatement.executeQuery()) {
                    // Agregar filas al modelo
                    while (resultSet.next()) {
                        Object[] fila = {
                            resultSet.getInt("id_transaccion"),
                            resultSet.getString("cuenta_origen"),
                            resultSet.getInt("monto"),
                            resultSet.getString("cuenta_destino"),
                            resultSet.getTimestamp("fecha_hora"),
                        };
                        String cuentaOrigen = resultSet.getString("cuenta_origen");
                        System.out.println("Cuenta origen: " + cuentaOrigen);
                        registro.addRow(fila);
                    }
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public VentanaHistorial(DefaultTableModel registro, Cliente cliente) {
        this.registro = registro;
        this.cliente = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        bntTransferir = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRegistro = new javax.swing.JTable();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        bntTransferir.setText("Transferir");
        bntTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTransferirActionPerformed(evt);
            }
        });

        btnHistorial.setText("Historial de Transferencias");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tableRegistro.setModel(tableRegistro.getModel());
        jScrollPane1.setViewportView(tableRegistro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntTransferir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicio)
                    .addComponent(bntTransferir)
                    .addComponent(btnHistorial)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        VentanaPrincipal ventanaPrincipal = new VentanaPrincipal(cliente);
        ventanaPrincipal.setVisible(true);
        // Cerrar la ventana
        dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void bntTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTransferirActionPerformed
        VentanaTransferir ventanaTransferir = new VentanaTransferir(cliente);
        ventanaTransferir.setVisible(true);
        // Cerrar la ventana
        dispose();
    }//GEN-LAST:event_bntTransferirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       JOptionPane.showMessageDialog(this, "Ha salido de la aplicación", "Información", JOptionPane.INFORMATION_MESSAGE);
       dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaHistorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntTransferir;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRegistro;
    // End of variables declaration//GEN-END:variables
}
